### ISSUE TITLE
Missing opcodes for NA

### ISSUE THREAD

**Issue by teralove** [teralove/inspect-dungeon-clears#1]
I only have NA opcodes on hand. ~~Add them to "protocol.329685.map"~~

~~C_DUNGEON_CLEAR_COUNT_LIST = 41958~~
~~S_DUNGEON_CLEAR_COUNT_LIST = 49654~~

**Comment by teralove** [comment]
~~New opcodes for NA. Add them to "protocol.330802.map"~~

~~C_DUNGEON_CLEAR_COUNT_LIST = 38719~~
~~S_DUNGEON_CLEAR_COUNT_LIST = 23198~~

**Comment by Joewwww** [comment]
Do u know the missing opcode for NA patch 69?

**Comment by teralove** [comment]
protocol.331937.map

C_USER_PAPERDOLL_INFO = 33837
S_USER_PAPERDOLL_INFO = 40664

**Comment by teralove** [comment]
Not atm
